version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/var/www/frontend
    ports:
      - 3000:3000
    tty: true
    # command: ["npm", "run", "start"]
    depends_on:
      - backend
