main:
  params: [event]
  steps:
    - log_event:
        call: sys.log
        args:
          text: ${event}
          severity: INFO

    - gather_data:
        assign:
          - bucket: ${event.data.bucket}
          - name: ${event.data.name}
          - message: ${"Received event " + event.type + " - " + bucket + ", " + name}

    - return_data:
        return: ${message}
